const {
	AUTH_KEY,
	JWT_ACCESS_AUDIENCE,
	JWT_DOMAIN,
	JWT_ID_AUDIENCE,
	JWT_ISSUER,
	JWT_RETURN,
	NETLIFY_DEV,
	PLANETSCALE_RO_URL,
	POSTMARK_SERVER_TOKEN,
	ROOT_URL
} = process.env as {
	AUTH_KEY: string;
	JWT_ACCESS_AUDIENCE: string;
	JWT_DOMAIN: string;
	JWT_ID_AUDIENCE: string;
	JWT_ISSUER: string;
	JWT_RETURN: string;
	NETLIFY_DEV: string;
	PLANETSCALE_RO_URL: string;
	POSTMARK_SERVER_TOKEN: string;
	ROOT_URL: string;
};

const DEV = NETLIFY_DEV === 'true';

export {
	AUTH_KEY,
	DEV,
	JWT_ACCESS_AUDIENCE,
	JWT_DOMAIN,
	JWT_ID_AUDIENCE,
	JWT_ISSUER,
	JWT_RETURN,
	PLANETSCALE_RO_URL,
	POSTMARK_SERVER_TOKEN,
	ROOT_URL
};
